### ISSUE TITLE
Apply calibration factor on each trace saved in mseed

### ISSUE THREAD

**Issue by LiSedZh** [obspy/obspy#1595]
Hello all,

I am pretty new to obspy (version 0.12.4, python 3.5.2, ubuntu 16.4) and I hope I am at the right spot to ask the question I have.

I have a huge volume of continuous seismic data which I need to analyze. As a first step I would like to archive my data coming from the digitizer in appropriate mseed slices. I have more than 30 stations and decided to produce 1 mseed file for each channel in a time interval (slice). Now, I would like to convert my int32 to volts as soon as I read my archived data in for further analysis. I saw that there is a neat calibration factor you can set in the mseed header which should be applied to each trace. 
![selection_004](https://cloud.githubusercontent.com/assets/23518522/20397247/5c7ba734-ace9-11e6-8498-f47113f9fcbb.png)
(Got this from: https://docs.obspy.org/packages/autogen/obspy.core.stream.read.html)

This would exactly be what I am looking for. However, I am somehow not able to get it working.

I do the following:

1. I load my data from the digitizer (int16) using f.read() and I produce a numpy array out of it (converted to int32). 

2. Then I write my mseed setting up my header like this:

`stats = {'network': 'GR', 'station': '16', 'location': '',
         '1': 'WLZ', 'npts': S_per_miniSEED, 'sampling_rate': S_rate, 'calib':0.03, 'apply_calib': True,
         'mseed': {'dataquality': 'Q'}}`

`stats['starttime'] = '2016-11-02T15:08:00.000000Z' # Recording time of first data point`

3. I merge everything to a stream object:
`st = Stream([Trace(data=trace1, header=stats)])`

4. I write the mseed
`st.write(file_name, format='MSEED',encoding='STEIM2')`

My header now looks like this:
```
 network: GR
         station: 16
        location: 
         channel: 
       starttime: 2016-11-02T15:08:00.000000Z
         endtime: 2016-11-02T15:08:19.999999Z
   sampling_rate: 1000000.0
           delta: 1e-06
            npts: 20000000
           calib: 0.03
               1: WLZ
     apply_calib: True
           mseed: AttribDict({'dataquality': 'Q'})
```

5. I read my newly generated mseed:
`st1 = read(file_name)`

My header now looks like this:

```
network: GR
         station: 16
        location: 
         channel: 
       starttime: 2016-11-02T15:08:00.000000Z
         endtime: 2016-11-02T15:08:19.999999Z
   sampling_rate: 1000000.0
           delta: 1e-06
            npts: 20000000
           calib: 1.0
         _format: MSEED
           mseed: AttribDict({'dataquality': 'Q', 'byteorder': '>', 'encoding': 'STEIM2', 'filesize': 22073344, 'record_length': 4096, 'number_of_records': 5389})
```

My "calib" parameter changed to 1.0 and the data remains exactly the same. Am I somehow misunderstanding the idea behind this calibration factor?

Thank you very much in advance for your help!

Cheers
Linus
