### ISSUE TITLE
Trace stats 'npts' attribute not calculated upon object instantiation

### ISSUE THREAD

**Issue by El-minadero** [obspy/obspy#2401]
obspy version: 1.1.1
python version: 3.7.3
platform: Linux Eementary OS, Juno 5.0
installed Obspy via conda

It looks like when making synthetic traces, the 'npts' header field is not being recalculated:
```python

from obspy.core import UTCDateTime
from obspy.core.trace import Stats
from obspy.core import Trace
import numpy as np

sampling_rate=250.0
stats = Stats(header={'sampling_rate':sampling_rate,
                          'starttime':UTCDateTime(0)})
data  = np.random.normal(0,1,size=(int(sampling_rate*60*60*24)))
trace = Trace(data=data,header= stats)
print(trace.stats)
print(trace.data.shape)

```

And the output is:

```
       network: 
         station: 
        location: 
        channel: 
       starttime: 1970-01-01T00:00:00.000000Z
         endtime: 1970-01-01T00:00:00.000000Z
   sampling_rate: 250.0
           delta: 0.004
            npts: 0
           calib: 1.0
(21600000,)
```
