### ISSUE TITLE
Unable to write new metadata trace tag with stats.update()

### ISSUE THREAD

**Issue by asthecroweflies** [obspy/obspy#2410]
So I'm wanting to add a class label tag to the MSEED metadata and have no problem doing so with:

```
    class_dict = {'class' : CLASS_TYPE}
    st[s].stats.update(class_dict)
```
I do this for all traces in a stream and write the resulting stream to a file. I can see the tag was successfully inserted if I print the stats of the newly created stream object:

```
print(updated_stream[0].stats)

output:
         network: SV
         station: OB15
        location: 
         channel: XNY
       starttime: 2018-11-28T00:24:57.485180Z
         endtime: 2018-11-28T00:24:57.579300Z
   sampling_rate: 100000.0
           delta: 1e-05
            npts: 9413
           calib: 1.0
         _format: MSEED
           class: ERT
           mseed: AttribDict({u'record_length': 4096, u'encoding': u'FLOAT64', 'filesize': 4784128, u'dataquality': u'D', u'number_of_records': 19L, u'byteorder': u'>'})

```

But when I save the stream and read the file the tag is not there:

```
updated_stream.write('updated_stream.mseed', format='MSEED')
new_stream = read('updated_stream.mseed')
print(new_stream[0].stats)

         network: SV
         station: OB15
        location: 
         channel: XNY
       starttime: 2018-11-28T00:24:57.485180Z
         endtime: 2018-11-28T00:24:57.579300Z
   sampling_rate: 100000.0
           delta: 1e-05
            npts: 9413
           calib: 1.0
         _format: MSEED
           mseed: AttribDict({u'record_length': 4096, u'encoding': u'FLOAT64', 'filesize': 77824, u'dataquality': u'D', u'number_of_records': 19L, u'byteorder': u'>'})
```

What am I missing?
